### ISSUE TITLE
2022 schedule and schedule comments

### ISSUE THREAD

**Issue by samumantha** [csc-training/GeoML#17]
Day 1: |   |  
-- | -- | --
Intro | 0:15 |  
L: ML intro: | 0:45 | Mats
L: ML classif/reg/clustering | 1:00 | Mats
E1: Clustering | 0:30 | Kylli
LUNCH |   |  
L: Data preparation | 0:35 | Kylli/ Samantha
E2: Vector data prep | 0:30 | Samantha
L: Shallow modelling models | 1:25 | Mats
Day2 |   |  
E4: Shallow modelling, regression | 0:30 | Samantha
E5: Shallow modelling, classification | 1:15 | Kylli
L: Intro to DL: | 0:45 | Markus
LUNCH |   |  
L: Fully connected neural networks | 0:30 | Markus
E6: Dense ML vector | 1:00 | Samantha
E7: Dense ML raster | 1:00 | Kylli
Day3: |   |  
L: CNN | 1:10 | Markus
L: Puhti overview (modules, partitions, job submission)  + GPU + batch jobs| 1:00 | Samantha / Markus
E8: CNN data preparations | 0:20 | Kylli
LUNCH |   |  
E9: Keras CNN: Segmentation | 2:10 | Kylli
L: GIS tools and other links | 0:20 | Samantha

Comments:
* Vector data preparation could have more time.
* Some lectures could be split into shorter parts and mixed with exercises.
* GIS tools and other links was 10 min, could have been longer and possibly more organized

**Comment by ktiits** [comment]
Keeping it in wiki.
